blank_issues_enabled: false
contact_links:
  - name: ğŸ¤ Community Discussions
    url: https://github.com/newtheatre/proscenium/discussions
    about: Ask questions and discuss ideas
  - name: ğŸ“– Documentation
    url: https://github.com/newtheatre/proscenium/wiki
    about: Check the project documentation
